name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Production to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: paradewisudaitb/frontend-wisjul21/wisjul21-fe
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "production"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run deployment script over SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker-compose pull
            docker-compose up --build -d --remove-orphans
