name: CI/CD
on:
  push:
    branches:
      - main # kita branch production-nya main
jobs:
  build-prod:
    runs-on: ubuntu-latest
    # ga butuh yg if itu
    steps:
      - uses: actions/checkout@master
      - name: Publish Production to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: paradewisudaitb/Frontend/wisjul21-fe
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "production"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build-prod]
    steps:
      - name: Run deployment script over SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "docker-compose pull && docker-compose build && docker-compose up -d --remove-orphans"
